CREATE TABLE COM_SCHEDULE_JOB 
(
   ID                   VARCHAR2(36)         NOT NULL,
   JOB_GROUP            VARCHAR2(36),
   JOB_NAME             VARCHAR2(128),
   JOB_TYPE             VARCHAR2(2),
   JOB_OBJECT           VARCHAR2(256),
   SHELL_PATH           VARCHAR2(256),
   CRON_EXPRESSION      VARCHAR2(128),
   STATUS               VARCHAR2(2),
   RUN_STATUS           VARCHAR2(2),
   LAST_RUN_START_TIME  DATE,
   LAST_RUN_END_TIME    DATE,
   RUN_RESULT           VARCHAR2(2),
   RUN_MESSAGE          VARCHAR2(4000),
   CREATED_TIME         DATE,
   CREATED_USER_ID      VARCHAR2(36),
   CREATED_USER_NAME    VARCHAR2(45),
   UPDATED_TIME         DATE,
   UPDATED_USER_ID      VARCHAR2(36),
   UPDATED_USER_NAME    VARCHAR2(45),
   CONSTRAINT PK_COM_SCHEDULE_JOB PRIMARY KEY (ID)
);

COMMENT ON TABLE COM_SCHEDULE_JOB IS
'定时任务表';

COMMENT ON COLUMN COM_SCHEDULE_JOB.ID IS
'id';

COMMENT ON COLUMN COM_SCHEDULE_JOB.JOB_GROUP IS
'任务组';

COMMENT ON COLUMN COM_SCHEDULE_JOB.JOB_NAME IS
'任务名称';

COMMENT ON COLUMN COM_SCHEDULE_JOB.JOB_TYPE IS
'任务类型:J:java对象,S:shell脚本';

COMMENT ON COLUMN COM_SCHEDULE_JOB.JOB_OBJECT IS
'根据任务类型，如果是java对象，为class名称，shell脚本，为shell文件的路径';

COMMENT ON COLUMN COM_SCHEDULE_JOB.SHELL_PATH IS
'shell脚本路径';

COMMENT ON COLUMN COM_SCHEDULE_JOB.CRON_EXPRESSION IS
'调度时间';

COMMENT ON COLUMN COM_SCHEDULE_JOB.STATUS IS
'A:启用,D:禁用';

COMMENT ON COLUMN COM_SCHEDULE_JOB.RUN_STATUS IS
'任务当前状态,A:常态,R:正在运行,P:暂停';

COMMENT ON COLUMN COM_SCHEDULE_JOB.LAST_RUN_START_TIME IS
'最后运行开始时间';

COMMENT ON COLUMN COM_SCHEDULE_JOB.LAST_RUN_END_TIME IS
'最后运行结束时间';

COMMENT ON COLUMN COM_SCHEDULE_JOB.RUN_RESULT IS
'运行结果:1:正常结束,0:有异常';

COMMENT ON COLUMN COM_SCHEDULE_JOB.RUN_MESSAGE IS
'异常信息';

COMMENT ON COLUMN COM_SCHEDULE_JOB.CREATED_TIME IS
'创建时间';

COMMENT ON COLUMN COM_SCHEDULE_JOB.CREATED_USER_ID IS
'创建人ID';

COMMENT ON COLUMN COM_SCHEDULE_JOB.CREATED_USER_NAME IS
'创建人名称';

COMMENT ON COLUMN COM_SCHEDULE_JOB.UPDATED_TIME IS
'修改时间';

COMMENT ON COLUMN COM_SCHEDULE_JOB.UPDATED_USER_ID IS
'修改人ID';

COMMENT ON COLUMN COM_SCHEDULE_JOB.UPDATED_USER_NAME IS
'修改人名称';
CREATE TABLE HIS_SCHEDULE_JOB_RUN 
(
   ID                   VARCHAR2(36)         NOT NULL,
   JOB_ID               VARCHAR2(36),
   JOB_TYPE             VARCHAR2(2),
   JOB_OBJECT           VARCHAR2(256),
   SHELL_PATH           VARCHAR2(256),
   CRON_EXPRESSION      VARCHAR2(128),
   RUN_START_TIME       DATE,
   RUN_END_TIME         DATE,
   RUN_RESULT           VARCHAR2(2),
   RUN_MESSAGE          VARCHAR2(4000),
   CONSTRAINT PK_HIS_SCHEDULE_JOB_RUN PRIMARY KEY (ID)
);

COMMENT ON TABLE HIS_SCHEDULE_JOB_RUN IS
'定时任务运行日志表';

COMMENT ON COLUMN HIS_SCHEDULE_JOB_RUN.ID IS
'id';

COMMENT ON COLUMN HIS_SCHEDULE_JOB_RUN.JOB_ID IS
'任务ID';

COMMENT ON COLUMN HIS_SCHEDULE_JOB_RUN.JOB_TYPE IS
'任务类型';

COMMENT ON COLUMN HIS_SCHEDULE_JOB_RUN.JOB_OBJECT IS
'任务执行对象';

COMMENT ON COLUMN HIS_SCHEDULE_JOB_RUN.SHELL_PATH IS
'shell脚本路径';

COMMENT ON COLUMN HIS_SCHEDULE_JOB_RUN.CRON_EXPRESSION IS
'调度时间';

COMMENT ON COLUMN HIS_SCHEDULE_JOB_RUN.RUN_START_TIME IS
'运行开始时间';

COMMENT ON COLUMN HIS_SCHEDULE_JOB_RUN.RUN_END_TIME IS
'运行结束时间';

COMMENT ON COLUMN HIS_SCHEDULE_JOB_RUN.RUN_RESULT IS
'运行结果';

COMMENT ON COLUMN HIS_SCHEDULE_JOB_RUN.RUN_MESSAGE IS
'异常信息';

ALTER TABLE HIS_SCHEDULE_JOB_RUN
   ADD CONSTRAINT FK_HIS_SCHE_REFERENCE_COM_SCHE FOREIGN KEY (JOB_ID)
      REFERENCES COM_SCHEDULE_JOB (ID);
